orange:
  description: "I just ate an orange!"
  created_at: <%= 10.minutes.ago %>

tau_manifesto:
  description: "Check out the @tauday site by @mhartl: http://tauday.com"
  created_at: <%= 3.years.ago %>

cat_video:
  description: "Sad cats are sad: http://youtu.be/PKffm2uI4dk"
  created_at: <%= 2.hours.ago %>

most_recent:
  description: "Writing a short test"
  created_at: <%= Time.zone.now %>